### ISSUE TITLE
Doesn't open on my mac  

### ISSUE THREAD

**Issue by yonigold1** [a8q/BlueSn0w#1]
the app doesn't launch on my mac regardless of what I do

**Comment by StrugglingDoge** [comment]
same -- on a HS Hackintosh and application is not supported apparently :/

**Comment by a8q** [comment]
This is now fixed with the RC2 re release [here](https://github.com/a8q/BlueSn0w/releases/tag/RC2Re). Sorry about this.

**Comment by StrugglingDoge** [comment]
yep, fixed it for me. But for some reason I cannot select an ipsw? I select an ipsw and it still says "Select an IPSW" and if I press the jailbreak button it fails saying failed to patch IBEC
